apiVersion: stackpulse.io/v1
kind: Step
metadata:
  version: 1.0.0
  name: "rundeck_job_metadata"
  description: "Get a specific job."
  vendor: rundeck
  type: hydration

envs:
  - name: HOST
    description: "Rundeck host name or IP."
    type: "string"
    required: true
    example: "rundeck.server"
  - name: PORT
    description: "Rundeck port."
    type: "string"
    required: true
    example: "4040"
  - name: AUTH_TOKEN
    description: "Token for authentication."
    type: "string"
    required: true
    example: "DRUVEuCdENoPkUpDkcDcdd6PeKkPdurc"
  - name: JOB_ID
    description: "Job ID"
    type: "string"
    required: true
    example: "3b6c19f6-41ee-475f-8fd0-8f1a26f27a9a"
  - name: HTTP_SCHEME
    description: "HTTP Request scheme. can be either 'http' or 'https'."
    type: "string"
    default: "https"
    example: "http"


outputs:
  - name: id
    description: "Job ID"
    type: "string"
    example: "846a2025-7895-4af2-a594-a0a9174339ec"
  - name: name
    description: "Job Name"
    type: "string"
    example: "Restart-Server"
  - name: group
    description: "Job group"
    type: "string"
    example: "GroupName"
  - name: project
    description: "Job project"
    type: "string"
    example: "anvil"
  - name: description
    description: "Job description"
    type: "string"
    example: "restart server job description"
  - name: href
    description: "Job HREF url"
    type: "string"
    example: "http://rundeck.server:4440/api/38/execution/88"
  - name: permalink
    description: "Permanent link to job"
    type: "string"
    example: "http://rundeck.server:4440/project/anvils/execution/show/88"
  - name: average_duration
    description: "Average duration of the job's executions, in milliseconds."
    type: "int"
    example: 45678
  - name: scheduled
    description: "Whether the job is scheduled to run."
    type: "bool"
    example: false
  - name: schedule_enabled
    description: "Whether schedualing is enabled for this job."
    type: "bool"
    example: false
  - name: enabled
    description: "Whether executing the job is enabled."
    type: "bool"
    example: true