apiVersion: stackpulse.io/v1
kind: Step
metadata:
  version: 1.0.0
  name: "victorops_incident_resolve"
  description: "Resolve an incident."
  vendor: victorops
  type: remediation 

envs:
  - name: VICTOROPS_API_ID
    description: "API ID to access VictorOps API."
    type: "string"
    required: true
  - name: VICTOROPS_API_KEY
    description: "API key to access VictorOps API."
    type: "string"
    required: true
  - name: INCIDENT_NUMBERS
    description: "Incident numbers to resolve. Can provide multiple values separated by ',' or a JSON string array."
    type: "json"
    required: true
  - name: USER_NAME
    description: "Displays the user who has resolved this incident."
    type: "string"
    required: true
  - name: RESOLVE_MESSAGE
    description: "Include this as the resolve message"
    type: "string"
    required: false

outputs:
  - name: incident_numbers
    description: "The numbers of the resolved incidents."
    type: "json"
    example: "[111,222]"
  - name: entity_ids
    description: "The unique identification of the entities being monitored that caused the incidents."
    type: "json"
    example: '["aa-bb-cc","dd-ee-ff"]'
  - name: api_object
    description: "Original api object as received from the API call."
    type: "json"
    example: '{"incidentNumber":"string","entityId":"string","cmdAccepted":true,"message":"string"}'