apiVersion: stackpulse.io/v1
kind: Step
metadata:
  name: "aws_cli_command"
  imageName: "amazon/aws-cli"
  description: "Generic AWS CLI command"
  vendor: aws
  type: advanced

args:
  - name: COMMAND
    description: "AWS specific command."
    type: "string"
    required: true
  - name: SUBCOMMAND
    description: "AWS subcommand."
    type: "string"
    required: true
  - name: OPTIONS
    description: "More command options (each argument should be separated in a different argument array item) "
    type: "string"
    required: true

outputs:
  - name: output
    description: "The AWS CLI command result. The format depends on the specific command."
    type: string
    example: '2021-01-05 15:33:36 aws-cloudtrail-logs-761268670892-ba2fb432'

integrations:
  - aws
