apiVersion: stackpulse.io/v1
kind: Step
metadata:
  version: 1.0.0
  name: "replace_string"
  description: "This step replaces sub-string or a regular expression by another sub-string for a given base64 string."
  vendor: custom
  type: custom

envs:
  - name: ORIGINAL_BASE64_STRING
    description: "The encoded base64 string to handle."
    type: "string"
    required: true
  - name: SUB_STR_SRC
    description: "The sub-string to replace."
    type: "string"
    required: true
  - name: SUB_STR_DEST
    description: "The sub-string to replace with."
    type: "string"
    required: true
  - name: REGEX
    type: bool
    description: "Whether the sub string source (SUB_STR_SRC) is a regular expression or not."