apiVersion: stackpulse.io/v1
kind: Step
metadata:
  name: "aws-detach-instances"
  imageName: "amazon/aws-cli"
  description: "Detach a volume from an instance."
  vendor: aws
  type: remediation

args:
  - name: command
    description: "AWS specific command."
    type: "string"
    required: true
    default: "ec2"
  - name: subcommand
    description: "AWS subcommand."
    type: "string"
    required: true
    default: "detach-volume"
  - name: --volume-id
    description: "The ID of the volume."
    required: true
    type: "string"
    default: "{{ .volumeID }}"
  - name: --instance-id
    description: "The ID of the instance. If you are detaching a Multi-Attach enabled volume, you must specify an instance ID."
    type: "string"
    default: "{{ .instanceID }}"
  - name: force
    description: "Forces detachment if the previous detachment attempt did not occur cleanly (for example, logging into an instance, unmounting the volume, and detaching normally). This option can lead to data loss or a corrupted file system. Use this option only as a last resort to detach a volume from a failed instance. The instance won't have an opportunity to flush file system caches or file system metadata. If you use this option, you must perform file system check and repair procedures."
    type: "string"
    default: "--force"

integrations:
  - aws
