apiVersion: stackpulse.io/v1
kind: Step
metadata:
  version: 1.0.0
  name: "greynoise_get_ip"
  description: "Retrieve information about an IP address."
  vendor: greynoise
  type: triage

envs:
  - name: IP
    description: "IP address."
    type: "string"
    required: true
    example: "8.8.8.8"
  - name: GN_API_KEY
    description: "Your GreyNoise API key for using the GreyNoise enterprise API. If not provided the community API will be used."
    type: "string"
    required: false


outputs:
  - name: name
    description: "Name of Organization that Owns the IP."
    type: "string"
    example: "Cloudflare"
  - name: noise
    description: "If true, this IP has been observed scanning the internet in the last 90 days."
    type: "boolean"
    example: "true"
  - name: riot
    description: "If true, this IP was found in the RIOT project dataset."
    type: "boolean"
    example: "true"
  - name: classification
    description: "The GreyNoise classification for this IP."
    type: "string"
    example: "malicious"
  - name: api_object
    description: "Object containing an the response from the VirusTotal API."
    type: "json"
    example: |
        {
            "ip": "1.1.1.1",
            "noise": false,
            "riot": true,
            "classification": "benign",
            "name": "Cloudflare",
            "link": "https://viz.greynoise.io/riot/1.1.1.1",
            "last_seen": "2020-01-01",
            "message" : "Success"
        }