apiVersion: stackpulse.io/v1
kind: Step
metadata:
  version: 1.0.0
  name: "stackpulse_page"
  description: "Page a person using a phone call or SMS and receive an acknowledgment."
  vendor: stackpulse
  type: notification
envs:
  - name: USER
    description: "The email of the user you want to notify. The user must set a phone number in his StackPulse account, otherwise the step will fail."
    type: "string"
    required: true
    example: "johndoe@stackpulse.io"
  - name: MESSAGE
    description: "Text will be sent to destination."
    type: "string"
    required: true
    example: "System UI is not working."
  - name: TYPE
    description: "Flow type."
    type: "string"
    default: "PHONE_CALL"
    example: "PHONE_CALL|SMS"
  - name: PHONE_NUMBER
    description: "Phone number to be directly paged. Can be used when a user has not set up a number in StackPulse. If used then the USER environment variable must not be used."
    type: "string"
    example: "+15555555555"
outputs:
  - name: acknowledged
    description: "Whether the person acknowledged the page. If the person did not acknowledge or any error occurred during the page, this will be false."
    type: "bool"
    example: 'true'