apiVersion: stackpulse.io/v1
kind: Step
metadata:
  version: 1.0.0
  name: "redis_get"
  description: "Perform Redis get call, (https://redis.io/commands/get)"
  vendor: redis
  type: hydration

envs:
  - name: REDIS_IP 
    description: "Destination redis IP address (required)"
    type: "string"
    required: true
    example: "127.0.0.1"
  - name: REDIS_USERNAME
    description: "The username to use for authentication with redis."
    type: "string"
    required: false
    example: 'myuser'
  - name: REDIS_PASSWORD
    description: "Destination redis password (optional)"
    type: "string"
    example: '{{ secret "REDIS_PASSWORD" }}'
  - name: REDIS_URL 
    description: "Redis url (required if there is no redis IP address specified)"
    type: "string"
    example: "redis://<username>:<password>@<host>:<port>/<database>"
  - name: KEY 
    description: "Item key"
    type: "string"
    required: true
    example: "mykey"

outputs:
  - name: output
    description: "Retrieved value."
    type: "string"
    example: "value"