apiVersion: stackpulse.io/v1
kind: Step
metadata:
  version: 1.0.0
  name: "ansible_awx_launch_job"
  description: "Run an AWX job template."
  vendor: ansible
  type: remediation

envs:
  - name: HOST
    description: "AWX host"
    type: "string"
    required: true
    example: "http://my.awx.host"
  - name: USERNAME
    description: "Username is used to authenticate. Must be supplied if the token is empty"
    type: "string"
    required: false
  - name: PASSWORD
    description: "Password is used to authenticate. Must be supplied if the token is empty"
    type: "string"
    required: false
  - name: TOWER_OAUTH_TOKEN
    description: "Token for authentication. Must be supplied if USERNAME and PASSWORD are empty"
    type: "string"
    required: false
  - name: INSECURE
    description: "Allow HTTPS insecure connection"
    type: "bool"
    required: false
    default: false
  - name: JOB
    description: "Job template ID or name to run"
    type: "string"
    required: true
  - name: WAIT
    description: "Should wait for job completion"
    type: "bool"
    required: false
    default: false
  - name: INVENTORY
    description: "the ID of the associated inventory"
    type: "string"
    required: false
  - name: MONITOR
    description: "If true, prints stdout of the launched job until it finishes"
    type: "bool"
    required: false
    default: false
  - name: SCM_BRANCH
    description: "Run on specific SCM brunch"
    type: "string"
    required: false
  - name: JOB_CHECK
    description: "Run in check mode"
    type: "bool"
    required: false
    default: false
  - name: VERBOSITY
    description: "Verbosity of the launched job"
    type: "int"
    required: false
    default: 0
  - name: EXTRA_VARS
    description: "JSON or yaml for extra vars for the job"
    type: "json"
    required: false
    example: '{"var":"value"}'
