---
apiVersion: stackpulse.io/v1
kind: Step
metadata:
  version: 1.0.0
  name: "bigquery_query"
  description: "Ad-hoc SQL query for BigQuery tables."
  vendor: bigquery
  type: triage
envs:
  - name: PROJECT
    description: "Google Cloud Project-ID"
    type: "string"
    required: true
  - name: QUERY
    description: "BigQuery SQL query"
    type: "string"
    required: true
